-- Users table seeds here (Example)
INSERT INTO users (name, email, password) VALUES ('Alice', 'jajjaa@hotmail.com', 'password');
INSERT INTO users (name, email, password) VALUES ('Kira', 'bigEater@gmail.com', 'password');
insert into users (name, email, password) values ('Symon Josefowicz', 'sjosefowicz0@newyorker.com', 'password');
insert into users (name, email, password) values ('Ximenez Jills', 'xjills1@topsy.com', 'password');
insert into users (name, email, password) values ('Robbyn Askam', 'raskam2@go.com', 'password');
insert into users (name, email, password) values ('Irv Aizikovitch', 'iaizikovitch3@123-reg.co.uk', 'password');
insert into users (name, email, password) values ('Loren Brevetor', 'lbrevetor4@vinaora.com', 'password');
insert into users (name, email, password) values ('Lionello Quillinane', 'lquillinane5@feedburner.com', 'password');
insert into users (name, email, password) values ('Richard Aire', 'raire6@google.pl', 'password');
insert into users (name, email, password) values ('Elnora Chaplain', 'echaplain7@amazonaws.com', 'password');
insert into users (name, email, password) values ('Sheba Fairburne', 'sfairburne8@infoseek.co.jp', 'password');
insert into users (name, email, password) values ('Kori Sharples', 'ksharples9@jimdo.com', 'password');
insert into users (name, email, password) values ('Meredithe Bernakiewicz', 'mbernakiewicza@google.com.hk', 'password');
insert into users (name, email, password) values ('Vito Plunkett', 'vplunkettb@si.edu', 'password');
insert into users (name, email, password) values ('Hildagard Caller', 'hcallerc@state.gov', 'password');
insert into users (name, email, password) values ('Rafi Gaunt', 'rgauntd@list-manage.com', 'password');
insert into users (name, email, password) values ('Tammy Cuffin', 'tcuffine@google.nl', 'password');
insert into users (name, email, password) values ('Liana Backshill', 'lbackshillf@foxnews.com', 'password');
insert into users (name, email, password) values ('Maxy Coughlan', 'mcoughlang@hud.gov', 'password');
insert into users (name, email, password) values ('Anette Waddicor', 'awaddicorh@utexas.edu', 'password');
insert into users (name, email, password) values ('Fowler Dornan', 'fdornani@liveinternet.ru', 'password');
insert into users (name, email, password) values ('Addy Izhaky', 'aizhakyj@addtoany.com', 'password');
insert into users (name, email, password) values ('Noble Pevreal', 'npevrealk@hao123.com', 'password');
insert into users (name, email, password) values ('Honey Gurling', 'hgurlingl@amazon.co.jp', 'password');
insert into users (name, email, password) values ('Tisha Mott', 'tmottm@pen.io', 'password');
insert into users (name, email, password) values ('Glenna Dallin', 'gdallinn@blinklist.com', 'password');
insert into users (name, email, password) values ('Elias Westnedge', 'ewestnedgeo@independent.co.uk', 'password');