INSERT INTO accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) VALUES (1, 'customer', '888 Owen Street, Vancouver, Canada', 'Jira Financial Experts', '2020-01-01', null, TRUE);
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (1, 'customer', '412 Butternut Way', null, '2005-08-09', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (2, 'customer', '073 Anderson Point', null, '2011-08-20', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (3, 'customer', '35843 Fremont Center', 'Twitterwire', '2013-03-30', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (4, 'customer', '2 Nancy Road', null, '2014-05-04', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (5, 'customer', '8 Heath Drive', null, '2015-11-11', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (6, 'customer', '99 Oxford Parkway', 'Cogidoo', '2010-01-24', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (7, 'customer', '8 Sutherland Parkway', null, '2016-05-06', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (8, 'customer', '8823 Northfield Avenue', null, '2013-07-17', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (9, 'customer', '190 Pennsylvania Avenue', null, '2009-09-23', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (10, 'customer', '076 Pleasure Crossing', null, '2017-06-09', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (11, 'customer', '139 Northview Place', null, '2012-01-15', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (12, 'customer', '92 Reindahl Circle', null, '2012-10-28', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (13, 'customer', '68 Lotheville Lane', null, '2008-03-20', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (14, 'customer', '95932 Hoepker Plaza', 'Divanoodle', '2020-08-15', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (15, 'customer', '73885 Waubesa Terrace', null, '2008-03-12', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (16, 'customer', '47 Meadow Valley Way', 'Divanoodle', '2011-04-15', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (17, 'customer', '6623 Meadow Ridge Circle', null, '2018-11-26', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (18, 'customer', '2 Brentwood Crossing', null, '2011-03-16', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (19, 'customer', '2 Sheridan Terrace', null, '2019-05-19', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (20, 'customer', '81445 Barby Road', 'Flipbug', '2019-04-21', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (21, 'customer', '32 Porter Parkway', null, '2014-06-22', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (22, 'customer', '24 Anhalt Park', 'Jazzy', '2020-05-18', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (23, 'customer', '854 Maple Place', null, '2016-05-31', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (24, 'customer', '152 Mifflin Road', null, '2017-05-05', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (25, 'customer', '9 Ohio Avenue', null, '2021-04-24', null, 'TRUE');
insert into accounts (owner_id, owner_type, address, company, date_joined, date_ended, active) values (26, 'customer', '9974 La Follette Point', 'Skiptube', '2016-08-02', null, 'TRUE');